
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ASSIGN_OP = 24;
  public static final int RIGHT_PAREN = 28;
  public static final int CARACTERE = 25;
  public static final int DGT = 40;
  public static final int MULT = 38;
  public static final int GE = 37;
  public static final int INTEGER = 5;
  public static final int TGT = 42;
  public static final int FOR = 10;
  public static final int MINUS = 31;
  public static final int WRITE = 16;
  public static final int NOT = 20;
  public static final int SEMICOLON = 27;
  public static final int AND = 18;
  public static final int DECIMALCONSTANT = 23;
  public static final int LT = 33;
  public static final int OR = 17;
  public static final int COMMA = 26;
  public static final int DIV = 39;
  public static final int BEGIN = 4;
  public static final int QUESTION_MARK = 44;
  public static final int PLUS = 32;
  public static final int DLT = 41;
  public static final int IF = 7;
  public static final int INTEGERCONSTANT = 22;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int DECIMAL = 6;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int TLT = 43;
  public static final int MOD = 19;
  public static final int EQ = 30;
  public static final int DECLARE = 3;
  public static final int COLON = 45;
  public static final int ELSE = 9;
  public static final int ACUTE_ACCENT = 47;
  public static final int READ = 15;
  public static final int BACKTICK = 46;
  public static final int TO = 13;
  public static final int WHILE = 14;
  public static final int THEN = 8;
  public static final int NE = 35;
  public static final int END = 11;
  public static final int LEFT_PAREN = 29;
  public static final int GT = 36;
  public static final int DO = 12;
  public static final int IDENTIFIER = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "DECLARE",
  "BEGIN",
  "INTEGER",
  "DECIMAL",
  "IF",
  "THEN",
  "ELSE",
  "FOR",
  "END",
  "DO",
  "TO",
  "WHILE",
  "READ",
  "WRITE",
  "OR",
  "AND",
  "MOD",
  "NOT",
  "IDENTIFIER",
  "INTEGERCONSTANT",
  "DECIMALCONSTANT",
  "ASSIGN_OP",
  "CARACTERE",
  "COMMA",
  "SEMICOLON",
  "RIGHT_PAREN",
  "LEFT_PAREN",
  "EQ",
  "MINUS",
  "PLUS",
  "LT",
  "LE",
  "NE",
  "GT",
  "GE",
  "MULT",
  "DIV",
  "DGT",
  "DLT",
  "TGT",
  "TLT",
  "QUESTION_MARK",
  "COLON",
  "BACKTICK",
  "ACUTE_ACCENT"
  };
}

